#!/usr/bin/env python3
"""Generate language-neutral and C protocol-v1 golden vectors."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import struct
import sys


HERE = Path(__file__).resolve().parent
TOOLS_DIR = HERE.parent / "tools"
sys.path.insert(0, str(TOOLS_DIR))

from oomwoo_mcu_frame import VERSION, encode_frame  # noqa: E402


MANIFEST_PATH = HERE / "protocol_v1.json"
JSON_OUTPUT_PATH = HERE / "golden_vectors_v1.json"
HEADER_OUTPUT_PATH = HERE / "golden_vectors_v1.h"


def _identifier(name: str) -> str:
    return re.sub(r"[^A-Za-z0-9]", "_", name).upper()


def _bytes_initializer(data: bytes) -> str:
    if not data:
        return "0x00u"
    return ", ".join(f"0x{byte:02x}u" for byte in data)


def build_vectors(manifest: dict[str, object]) -> list[dict[str, object]]:
    if manifest["wire_version"] != VERSION:
        raise ValueError(
            f"manifest wire version {manifest['wire_version']} != codec {VERSION}"
        )

    vectors: list[dict[str, object]] = []
    for message in manifest["messages"]:
        if message["payload_status"] != "defined":
            continue
        payload_format = message["struct_format"]
        for sample in message["samples"]:
            payload = (
                struct.pack(payload_format, *sample["values"])
                if payload_format
                else b""
            )
            frame = encode_frame(
                message["id"],
                payload,
                sequence=sample["sequence"],
                flags=sample["flags"],
            )
            vectors.append(
                {
                    "name": sample["name"],
                    "message_name": message["name"],
                    "message_type": message["id"],
                    "sequence": sample["sequence"],
                    "flags": sample["flags"],
                    "payload_hex": payload.hex(),
                    "frame_hex": frame.hex(),
                }
            )
    return vectors


def render_json(manifest: dict[str, object], vectors: list[dict[str, object]]) -> str:
    document = {
        "generated_from": MANIFEST_PATH.name,
        "wire_version": manifest["wire_version"],
        "vectors": vectors,
        "open_messages": [
            {
                "name": message["name"],
                "message_type": message["id"],
                "reason": message["open_reason"],
            }
            for message in manifest["messages"]
            if message["payload_status"] == "open"
        ],
    }
    return json.dumps(document, indent=2) + "\n"


def render_header(vectors: list[dict[str, object]]) -> str:
    lines = [
        "/* Generated by generate_vectors.py. Do not edit manually. */",
        "#ifndef OOMWOO_GOLDEN_VECTORS_V1_H",
        "#define OOMWOO_GOLDEN_VECTORS_V1_H",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "typedef struct {",
        "  const char *name;",
        "  uint16_t message_type;",
        "  uint16_t sequence;",
        "  uint8_t flags;",
        "  const uint8_t *payload;",
        "  size_t payload_length;",
        "  const uint8_t *frame;",
        "  size_t frame_length;",
        "} oomwoo_golden_vector_t;",
        "",
    ]

    for vector in vectors:
        identifier = _identifier(vector["name"])
        payload = bytes.fromhex(vector["payload_hex"])
        frame = bytes.fromhex(vector["frame_hex"])
        lines.extend(
            [
                f"static const uint8_t payload_{identifier}[] = {{",
                f"  {_bytes_initializer(payload)}",
                "};",
                f"static const uint8_t frame_{identifier}[] = {{",
                f"  {_bytes_initializer(frame)}",
                "};",
                "",
            ]
        )

    lines.append("static const oomwoo_golden_vector_t oomwoo_golden_vectors[] = {")
    for vector in vectors:
        identifier = _identifier(vector["name"])
        payload_length = len(bytes.fromhex(vector["payload_hex"]))
        lines.extend(
            [
                "  {",
                f'    "{vector["name"]}",',
                f'    0x{vector["message_type"]:04x}u,',
                f'    {vector["sequence"]}u,',
                f'    {vector["flags"]}u,',
                f"    payload_{identifier},",
                f"    {payload_length}u,",
                f"    frame_{identifier},",
                f"    sizeof(frame_{identifier})",
                "  },",
            ]
        )
    lines.extend(
        [
            "};",
            "",
            "#define OOMWOO_GOLDEN_VECTOR_COUNT \\",
            "  (sizeof(oomwoo_golden_vectors) / sizeof(oomwoo_golden_vectors[0]))",
            "",
            "#endif",
            "",
        ]
    )
    return "\n".join(lines)


def _check_file(path: Path, expected: str) -> bool:
    if not path.exists() or path.read_text(encoding="utf-8") != expected:
        print(f"stale generated file: {path}", file=sys.stderr)
        return False
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check", action="store_true", help="fail instead of updating stale outputs"
    )
    args = parser.parse_args()

    manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    vectors = build_vectors(manifest)
    json_output = render_json(manifest, vectors)
    header_output = render_header(vectors)

    if args.check:
        return 0 if _check_file(JSON_OUTPUT_PATH, json_output) else 1

    JSON_OUTPUT_PATH.write_text(json_output, encoding="utf-8")
    HEADER_OUTPUT_PATH.write_text(header_output, encoding="utf-8")
    print(f"generated {len(vectors)} vectors")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
